sudo : required
language: generic
services:
  - docker

before_install:
  - docker build -t rpawan48/docker_react -f Dockerfile.dev . 

script:
  - docker run -e CI=true rpawan48/docker_react npm run test