sudo : required
language: generic
services:
  - docker

before_install:
  - docker build -t rpawan48/docker_react -f Dockerfile.dev .-t 

script:
  - docker run rpawan48/docker_react npm run test -- --coverage